### ISSUE TITLE
Consider adding the Cisco Certified CyberOps Professional Certification

### ISSUE THREAD

**Issue by santosomar** [sinecurelife/SecCertRoadmapHTML#10]
Cisco Certified CyberOps Professional Certification is now active since Nov 2020:
https://www.cisco.com/c/en/us/training-events/training-certifications/certifications/professional/cyberops-professional.html

This certification should be added under Security Operations.

**Comment by sinecurelife** [comment]
Thanks for letting me know about this one. It has been added.
