### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by victorwestmann** [sinecurelife/SecCertRoadmapHTML#25]
I just had to pass by and leave a comment this is stunning and that you are doing a great job!
Just though you could appreciate some sort of compliment for this awesome looking project you did. Do you know if there are other diagrams/maps/schematics of certifications on GitHub?

**Comment by sinecurelife** [comment]
I haven't looked for any, but maybe! I do have another git for the web app version of this chart but I haven't made any progress on it.

https://github.com/sinecurelife/SecCertRoadmap
